name: Build Docs

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  docs:
    uses: moigagoo/nimbus-common-workflow/.github/workflows/docs.yml@feature/reusable_docs_workflow
    with:
      mdbook-version: "0.5.2"
      mdbook-preprocessors: >-
        [
          "mdbook-open-on-gh@3.0.0",
          "mdbook-toc@0.15.3",
          "mdbook-admonish@1.20.0"
        ]
